name: Build Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymavlink pyserial pyinstaller customtkinter

    # Собираем со всеми потрохами библиотеки pymavlink, включая генераторы и диалекты
    - name: Build with PyInstaller
      run: |
        $pymavlink_path = python -c "import pymavlink, os; print(os.path.dirname(pymavlink.__file__))"
        echo "Pymavlink path found: $pymavlink_path"
        pyinstaller --onefile --noconsole --hidden-import=pymavlink --hidden-import=pymavlink.dialects --hidden-import=pymavlink.dialects.v20 --hidden-import=pymavlink.dialects.v20.ardupilotmega --add-data "$pymavlink_path;pymavlink" foxeer_tester.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/foxeer_tester.exe
